[project]
name = "epsi-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "e-psi-lon" }
]
dependencies = [
    "aiocache[memcached]>=0.12.3",
    "aiodns>=3.5.0",
    "aiomultiprocess>=0.9.1",
    "aiomysql>=0.2.0",
    "audioop-lts>=0.2.1",
    "brotlipy>=0.7.0",
    "charset-normalizer>=3.4.2",
    "psutil>=7.0.0",
    "py-cord>=2.6.1",
    "pynacl>=1.5.0",
    "python-dotenv>=1.1.1",
    "python-ffmpeg>=2.0.12",
    "pytubefix>=9.2.1",
    "quart>=0.20.0",
    "quart-session>=3.0.0",
    "tortoise-orm>=0.25.1",
]


[project.scripts]
epsi-bot = "epsi_bot.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["epsi_bot/**"]

[dependency-groups]
dev = [
    "aiosqlite>=0.21.0",
    "mypy>=1.16.1",
    "types-psutil>=7.0.0",
    "pytest>=8.4.1",
    "pytest-aio>=1.9.0",
    "pytest-cov>=6.2.0",
    "pytest-mock>=3.14.1",
]
