[project]
name = "epsi-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "e-psi-lon" }
]
dependencies = [
    "aiocache[memcached]>=0.12.3",
    "aiodns>=4.0.4",
    "aiomultiprocess>=0.9.1",
    "aiomysql>=0.3.2",
    "audioop-lts>=0.2.2",
    "charset-normalizer>=3.4.9",
    "psutil>=7.2.2",
    "py-cord>=2.8.1",
    "pydantic>=2.13.4",
    "pynacl>=1.6.2",
    "python-dotenv>=1.2.2",
    "python-ffmpeg>=2.0.12",
    "pytubefix>=10.10.1",
    "quart>=0.21.0",
    "quart-session>=3.0.0",
    "tortoise-orm==1.1.7",
]


[project.scripts]
epsi-bot = "epsi_bot.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.extra-build-dependencies]
"quart-session" = ["setuptools"]

[tool.hatch.build]
include = ["epsi_bot/**"]

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "mypy>=2.3.0",
    "types-psutil>=7.2.2.20260518",
    "pytest>=9.1.1",
    "pytest-aio>=2.1.7",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.16.0",
    "pre-commit>=4.6.1",
]


[tool.ruff.format]
indent-style = "tab"
