from typing import Any, Protocol


class CacheProtocol(Protocol):
	async def get_audio(self, key: str, **kwargs: Any) -> Any: ...
	async def set_audio(
		self, key: str, value: Any, ttl: int = 3600, **kwargs: Any
	) -> None: ...
	async def exists(self, key: str, **kwargs: Any) -> Any: ...
	async def clear(self, **kwargs: Any) -> None: ...
